Makefile: bump poetry's version
I got the following error when running `make install`:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry-plugin-export 1.3.1 requires poetry<2.0.0,>=1.3.0, but you have poetry 1.2.0a2 which is incompatible.